### ISSUE TITLE
name 'standardize_lora_key_format' is not defined

### ISSUE THREAD

**Issue by BenDes21** [zer0int/ComfyUI-HunyuanVideo-Nyan#4]
Hello, getting this error with the workflow correctly setup with all files

**Comment by zer0int** [comment]
Please update - should be fixed now! If not, please let me know.

**Comment by BenDes21** [comment]
same error

**Comment by BenDes21** [comment]
> Please update - should be fixed now! If not, please let me know.

![dd](https://github.com/user-attachments/assets/d576124d-fbe2-40da-a4bb-41e6d276105b)


same error

**Comment by zer0int** [comment]
Can you check you have [this](https://github.com/zer0int/ComfyUI-HunyuanVideo-Nyan/blob/5cd987ab1b267612cd0a3b00fe39bf1fd3fc6011/ComfyUI-HunyuanVideo-Nyan/hynyan.py#L56) in your hynyan.py file?

You can also just copy-and-paste this to the top of the file:

```
def filter_state_dict_by_blocks(state_dict, blocks_mapping):
    filtered_dict = {}

    for key in state_dict:
        if 'double_blocks.' in key or 'single_blocks.' in key:
            block_pattern = key.split('diffusion_model.')[1].split('.', 2)[0:2]
            block_key = f'{block_pattern[0]}.{block_pattern[1]}.'

            if block_key in blocks_mapping:
                filtered_dict[key] = state_dict[key]

    return filtered_dict

def standardize_lora_key_format(lora_sd):
    new_sd = {}
    for k, v in lora_sd.items():
        # Diffusers format
        if k.startswith('transformer.'):
            k = k.replace('transformer.', 'diffusion_model.')
        new_sd[k] = v
    return new_sd
```

I have tried with the LoRA from [here](https://huggingface.co/Kijai/HunyuanVideo_comfy/tree/main), and it worked fine for me.

**Comment by BenDes21** [comment]
> def filter_state_dict_by_blocks(state_dict, blocks_mapping):
>     filtered_dict = {}
> 
>     for key in state_dict:
>         if 'double_blocks.' in key or 'single_blocks.' in key:
>             block_pattern = key.split('diffusion_model.')[1].split('.', 2)[0:2]
>             block_key = f'{block_pattern[0]}.{block_pattern[1]}.'
> 
>             if block_key in blocks_mapping:
>                 filtered_dict[key] = state_dict[key]
> 
>     return filtered_dict
> 
> def standardize_lora_key_format(lora_sd):
>     new_sd = {}
>     for k, v in lora_sd.items():
>         # Diffusers format
>         if k.startswith('transformer.'):
>             k = k.replace('transformer.', 'diffusion_model.')
>         new_sd[k] = v
>     return new_sd

seems to work now, thanks
